import streamlit as st

# =========================
# Page Configuration
# =========================
st.set_page_config(
    page_title="Borrower Scoring Tool",
    page_icon="📊",
    layout="centered",
)

# =========================
# Header
# =========================
st.title("📊 Semi-Automated Borrower Scoring Tool")
st.caption(
    "Internal Prototype • Five C Credit Framework • Version 1.0"
)

st.markdown("---")

# =========================
# Tool Overview
# =========================
st.subheader("🔍 Tool Overview")

st.markdown(
    """
This internal tool is designed to **support and standardise borrower assessments**
by applying the **Five C credit framework** in a semi-automated manner.

The objective is **not** to replace credit judgement,  
but to provide a **structured, transparent and repeatable scoring baseline**
to assist decision-making.
"""
)

# =========================
# Current Scope
# =========================
st.subheader("📌 Current Scope (Prototype V1)")

st.markdown(
    """
✔ Implements **one component** of the Five C framework as a proof-of-concept  
✔ Focuses on **scoring logic, transparency, and UI flow**  
✔ Designed for **internal use only**
"""
)

# Optional: visual emphasis
st.info(
    "🧪 Prototype status: Logic and thresholds are subject to change and validation."
)

# =========================
# Entry Point
# =========================
st.subheader("🚀 Get Started")

st.markdown(
    """
To begin a borrower assessment, proceed to the scoring section using the navigation panel.

The current version allows you to:
- Input key borrower attributes  
- Generate a **component-level score**  
- Review how individual factors contribute to the result  
"""
)

# =========================
# Methodology Snapshot
# =========================
st.subheader("📐 Methodology Snapshot")

st.markdown(
    """
The tool follows the **Five C lending framework**:

- **Character** – borrower reliability and behavioural indicators  
- **Capacity** – ability to service debt  
- **Capital** – borrower financial contribution  
- **Collateral** – asset security  
- **Conditions** – external and loan-specific factors  

> Version 1 implements **Collateral** as the first component.
"""
)

# =========================
# Get Started Button
# =========================
st.markdown("---")

if st.button("▶ Get Started", use_container_width=True):
    st.switch_page("pages/1_Collateral.py")

# =========================
# Disclaimer
# =========================
st.markdown("---")

st.warning(
    """
**Disclaimer**

This tool is a **decision-support system only**.  
Scores generated by this application should **not** be used as the sole basis
for lending decisions and must be reviewed alongside full credit assessment
procedures and professional judgement.
"""
)

# =========================
# Footer
# =========================
st.caption(
    "Prototype V1 • Developed by Frank • Streamlit Web Application"
)
